"""Add notes column to Todo

Revision ID: 285026c64bf9
Revises: 4c79c9a155d5
Create Date: 2023-06-18 00:05:28.228459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285026c64bf9'
down_revision = '4c79c9a155d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
